---
version: '3.8'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${ODOO_PROJECT}_db
    user: "${POSTGRES_UID}:${POSTGRES_GID}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always             # run as a service
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
      - ${POSTGRES_INIT}:/docker-entrypoint-initdb.d
    userns_mode: host
  odoo17:
    image: odoo:devs_${ODOO_VERSION}
    container_name: ${ODOO_PROJECT}_${ODOO_VERSION}
    user: "${ODOO_UID}:${ODOO_GID}"
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069" # web/api
      - "${ODOO_CHAT}:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - TARGET_UID=1000
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB:-SAASDB}
      - DB_TEMPLATE=template0
      - INIT=${ODOO_INIT:-False}
      - BATCH=${ODOO_BATCH:-False}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${ODOO_BACKUPS}:/backups
      - ${ODOO_APPS}:/mnt/extra-addons
      - ${ODOO_ETC}:/etc/odoo
      - ${ODOO_DATA}:/data
      - ${ODOO_WEB}:/var/lib/odoo
    userns_mode: host
    restart: always             # run as a service
